In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv('play_tennis.csv')
df.head()

  day   outlook  temp humidity    wind play
0  D1     Sunny   Hot     High    Weak   No
1  D2     Sunny   Hot     High  Strong   No
2  D3  Overcast   Hot     High    Weak  Yes
3  D4      Rain  Mild     High    Weak  Yes
4  D5      Rain  Cool   Normal    Weak  Yes

In [3]:
df.drop(columns=['day'], inplace=True)

In [4]:
df.head()

    outlook  temp humidity    wind play
0     Sunny   Hot     High    Weak   No
1     Sunny   Hot     High  Strong   No
2  Overcast   Hot     High    Weak  Yes
3      Rain  Mild     High    Weak  Yes
4      Rain  Cool   Normal    Weak  Yes

In [5]:
# problem 1

# Outlook=sunny, temp=hot, humidity=high, wind=weak
# Play or No Play

In [6]:
# solution 

# P(yes | sunny, hot, high, weak) = P(sunny | yes) * P(hot | yes) * P(high | yes) * P(weak | yes)

# P(No | sunny, hot high, weak) = P(sunny | no) * P(hot | no) * P(high | no) * P(weak | no)

In [7]:
# P(Yes)
# P(No)

In [8]:
df['play'].value_counts()

play
Yes    9
No     5
Name: count, dtype: int64

In [9]:
PYes = 9/14
PNo = 5/14

In [10]:
# Outlook

pd.crosstab(df['outlook'], df['play'])

play      No  Yes
outlook
Overcast   0    4
Rain       2    3
Sunny      3    2

In [11]:
POvercastNo = 0
POvercastYes = 4/9

PRainNo = 2/5
PRainYes = 3/9

PSunnyNo = 3/5
PSunnyYes = 2/9

In [12]:
# Temp

pd.crosstab(df['temp'], df['play'])

play  No  Yes
temp
Cool   1    3
Hot    2    2
Mild   2    4

In [13]:
PCoolNo = 1/5
PCoolYes = 3/9

PHotNo = 2/5
PHotYes = 2/9

PMildNo = 2/5
PMildYes = 4/9

In [14]:
# Humidity

pd.crosstab(df['humidity'], df['play'])

play      No  Yes
humidity
High       4    3
Normal     1    6

In [15]:
PHighNo = 4/5
PHighYes = 3/9

PNormalNo = 1/5
PNormalYes = 6/9

In [16]:
# Wind

pd.crosstab(df['wind'], df['play'])

play    No  Yes
wind
Strong   3    3
Weak     2    6

In [17]:
PStrongNo = 3/5
PStrongYes = 3/9

PWeakNo = 2/5
PWeakYes = 6/9

In [18]:
# Outlook=sunny, temp=hot, humidity=high, wind=weak

Pyes = PYes * PSunnyYes * PHotYes * PHighYes * PWeakYes
print(Pyes)

0.007054673721340388

In [19]:
Pno = PNo * PSunnyNo * PHotNo * PHighNo * PWeakNo
print(Pno)

0.02742857142857143

In [20]:
# Since Pno is > Pyes
# Answer will be NO